apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault-gitlab-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-gitlab-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
