{{- if and (not .Values.gitlabToken.existingSecret) .Values.gitlabToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-gitlab-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-gitlab-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.gitlabToken.key }}: {{ .Values.gitlabToken.value | quote }}
{{- end }}
