apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-gitlab-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault-gitlab-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "vault-gitlab-operator.selectorLabels" . | nindent 4 }}
